import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/usermenu/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        {/* make changes on this but do not know why and i am also not intersed to know*/}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
