import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/usermenu/Providers";

export const metadata: Metadata = {
  title: "Tech Cafe GEC Raipur",
  description: "Generated by CoWebd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </head>
      <body className="antialiased font-sans">
        {/* make changes on this but do not know why and i am also not intersed to know*/}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
